
//
println("Test Date type");
println("=========================================================");


// Day in milliseconds
var DAY_TIME = 24 * 60 * 60 * 1000;
println("DAY_TIME = " + DAY_TIME);


// new date
var date = Date(2001, 12, 31);


// get attributes (year, month, day)
assert(date.getYear() == 2001);
assert(date.getMonth() == 12);
assert(date.getDay() == 31);


// shift days (+/-)
date = date + DAY_TIME; // +1 day
assert(date.getYear() == 2002);
assert(date.getMonth() == 1);
assert(date.getDay() == 1);

date = date + DAY_TIME; // +1 day
assert(date.getYear() == 2002);
assert(date.getMonth() == 1);
assert(date.getDay() == 2);

date = date + (DAY_TIME * 3); // +3 days
assert(date.getYear() == 2002);
assert(date.getMonth() == 1);
assert(date.getDay() == 5);

date = date - (DAY_TIME * 2); // -2 days
assert(date.getYear() == 2002);
assert(date.getMonth() == 1);
assert(date.getDay() == 3);


// delta time (1 day = DAY_TIME)
var date1 = Date(2001, 1, 1);
var date2 = Date(2001, 1, 4);
var time1 = date1.getTime();
var time2 = date2.getTime();
var time = time2 - time1; // delta time

assert(time == (DAY_TIME * 3)); // 3 days
assert(date2 > date1);


// set/get attributes (year, month, day)
date = Date(2015, 11, 20);

date.setYear(2016);
assert(date.getYear() == 2016);

date.setMonth(12);
assert(date.getMonth() == 12);

date.setDay(21);
assert(date.getDay() == 21);


// check time
var oldTime = date.getTime(); 
date.setTime(oldTime);

var newTime = date.getTime();
assert(oldTime == newTime);
assert(date.getYear() == 2016);
assert(date.getMonth() == 12);
assert(date.getDay() == 21);


// change time (+days)
time = date.getTime();
date.setTime(time + (DAY_TIME * 7)); // +7 days

assert(date.getYear() == 2016);
assert(date.getMonth() == 12);
assert(date.getDay() == 28);

// change time (-days)
time = date.getTime();
date.setTime(time - (DAY_TIME * 5)); // -5 days

assert(date.getYear() == 2016);
assert(date.getMonth() == 12);
assert(date.getDay() == 23);

// get/set by [] 
time = date.getTime();

assert(date["year"] == 2016);
assert(date["month"] == 12);
assert(date["day"] == 23);
assert(date["time"] == time);

// set new attributes
date["year"] = 2000;
date["month"] = 10;
date["day"] = 20;

// check new attributes
assert(date["year"] == 2000);
assert(date["month"] == 10);
assert(date["day"] == 20);

// set new time
date["time"] = time;

// check new attributes and time
assert(date["year"] == 2016);
assert(date["month"] == 12);
assert(date["day"] == 23);
assert(date["time"] == time);
