
//
println("Test Date type");

//
var dayTime = 24 * 60 * 60 * 1000;
var d = Date(2001, 12, 31);

assert(d.getYear() == 2001);
assert(d.getMonth() == 12);
assert(d.getDay() == 31);

d = d + dayTime; // +1 day
assert(d.getYear() == 2002);
assert(d.getMonth() == 1);
assert(d.getDay() == 1);

d = d + dayTime; // +1 day
assert(d.getYear() == 2002);
assert(d.getMonth() == 1);
assert(d.getDay() == 2);

d = d + (dayTime * 3); // +3 days
assert(d.getYear() == 2002);
assert(d.getMonth() == 1);
assert(d.getDay() == 5);

d = d - (dayTime * 2); // -2 days
assert(d.getYear() == 2002);
assert(d.getMonth() == 1);
assert(d.getDay() == 3);
