

//
println("Test Date type");
println("=========================================================");


// Day in milliseconds
var DAY_TIME = 24 * 60 * 60 * 1000;
println("DAY_TIME = " + DAY_TIME);


// new date
var date = Date(2001, 12, 31);


// get attributes (year, month, day)
assert(date.getYear() == 2001);
assert(date.getMonth() == 12);
assert(date.getDay() == 31);


// shift days (+/-)
date = date + DAY_TIME; // +1 day
assert(date.getYear() == 2002);
assert(date.getMonth() == 1);
assert(date.getDay() == 1);

date = date + DAY_TIME; // +1 day
assert(date.getYear() == 2002);
assert(date.getMonth() == 1);
assert(date.getDay() == 2);

date = date + (DAY_TIME * 3); // +3 days
assert(date.getYear() == 2002);
assert(date.getMonth() == 1);
assert(date.getDay() == 5);

date = date - (DAY_TIME * 2); // -2 days
assert(date.getYear() == 2002);
assert(date.getMonth() == 1);
assert(date.getDay() == 3);


// delta time (1 day = DAY_TIME)
var date1 = Date(2001, 1, 1);
var date2 = Date(2001, 1, 4);
var time1 = date1.getTime();
var time2 = date2.getTime();
var time = time2 - time1; // delta time

assert(time == (DAY_TIME * 3)); // 3 days
assert(date2 > date1);


// set/get attributes (year, month, day)
date = Date(2015, 11, 20);

date.setYear(2016);
assert(date.getYear() == 2016);

date.setMonth(12);
assert(date.getMonth() == 12);

date.setDay(21);
assert(date.getDay() == 21);


// check time
var oldTime = date.getTime(); 
date.setTime(oldTime);

var newTime = date.getTime();
assert(oldTime == newTime);
assert(date.getYear() == 2016);
assert(date.getMonth() == 12);
assert(date.getDay() == 21);


// change time (+days)
time = date.getTime();
date.setTime(time + (DAY_TIME * 7)); // +7 days

assert(date.getYear() == 2016);
assert(date.getMonth() == 12);
assert(date.getDay() == 28);

// change time (-days)
time = date.getTime();
date.setTime(time - (DAY_TIME * 5)); // -5 days

assert(date.getYear() == 2016);
assert(date.getMonth() == 12);
assert(date.getDay() == 23);

// get/set by [] 
time = date.getTime();

assert(date["year"] == 2016);
assert(date["month"] == 12);
assert(date["day"] == 23);
assert(date["time"] == time);

// set new attributes
date["year"] = 2000;
date["month"] = 10;
date["day"] = 20;

// check new attributes
assert(date["year"] == 2000);
assert(date["month"] == 10);
assert(date["day"] == 20);

// set new time
date["time"] = time;

// check new attributes and time
assert(date["year"] == 2016);
assert(date["month"] == 12);
assert(date["day"] == 23);
assert(date["time"] == time);


// now Date
date1 = Date();
date2 = Date(date1.getYear(), date1.getMonth(), date1.getDay());

println(date1.getTime());
println(date2.getTime());

// truncate time
assert((Date(date1.getTime() + 10)).getTime() == date1.getTime());

assert(date1.getTime() - date2.getTime() == 0);
assert(Date(1970, 1, 1).getTime() == 0);


println(DateTime(2016, 12, 1, 17, 20));


var dateTime = DateTime(2016, 12, 31, 17, 20, 40, 120);
println(dateTime);

// +50 ms
dateTime = dateTime + 50;
println(dateTime);

// +1 day
dateTime = dateTime + DAY_TIME; 
println(dateTime);

assert(dateTime["year"] == 2017);
assert(dateTime["month"] == 1);
assert(dateTime["day"] == 1);
assert(dateTime["hour"] == 17);
assert(dateTime["minute"] == 20);
assert(dateTime["second"] == 40);
assert(dateTime["millisecond"] == 170);

assert(dateTime.getYear() == 2017);
assert(dateTime.getMonth() == 1);
assert(dateTime.getDay() == 1);
assert(dateTime.getHour() == 17);
assert(dateTime.getMinute() == 20);
assert(dateTime.getSecond() == 40);
assert(dateTime.getMillisecond() == 170);


// modify
dateTime["year"] = 2015;
dateTime["month"] = 3;
dateTime["day"] = 15;
dateTime["hour"] = 23;
dateTime["minute"] = 47;
dateTime["second"] = 34;
dateTime["millisecond"] = 113;

// check modify
assert(dateTime["year"] == 2015);
assert(dateTime["month"] == 3);
assert(dateTime["day"] == 15);
assert(dateTime["hour"] == 23);
assert(dateTime["minute"] == 47);
assert(dateTime["second"] == 34);
assert(dateTime["millisecond"] == 113);

//
dateTime = DateTime(1900, 7, 20); 

assert(dateTime["year"] == 1900);
assert(dateTime["month"] == 7);
assert(dateTime["day"] == 20);
assert(dateTime["hour"] == 0);
assert(dateTime["minute"] == 0);
assert(dateTime["second"] == 0);
assert(dateTime["millisecond"] == 0);

//
dateTime = DateTime(1900, 7, 20, 17);

assert(dateTime["year"] == 1900);
assert(dateTime["month"] == 7);
assert(dateTime["day"] == 20);
assert(dateTime["hour"] == 17);
assert(dateTime["minute"] == 0);
assert(dateTime["second"] == 0);
assert(dateTime["millisecond"] == 0);

//
dateTime = DateTime(1900, 7, 20, 17, 18);

assert(dateTime["year"] == 1900);
assert(dateTime["month"] == 7);
assert(dateTime["day"] == 20);
assert(dateTime["hour"] == 17);
assert(dateTime["minute"] == 18);
assert(dateTime["second"] == 0);
assert(dateTime["millisecond"] == 0);

//
dateTime = DateTime(1900, 7, 20, 17, 18, 19);

assert(dateTime["year"] == 1900);
assert(dateTime["month"] == 7);
assert(dateTime["day"] == 20);
assert(dateTime["hour"] == 17);
assert(dateTime["minute"] == 18);
assert(dateTime["second"] == 19);
assert(dateTime["millisecond"] == 0);

//
dateTime = DateTime(1900, 7, 20, 17, 18, 19, 20);

assert(dateTime["year"] == 1900);
assert(dateTime["month"] == 7);
assert(dateTime["day"] == 20);
assert(dateTime["hour"] == 17);
assert(dateTime["minute"] == 18);
assert(dateTime["second"] == 19);
assert(dateTime["millisecond"] == 20);

var t = Time(10, 20, 30, 120);
println(t);


assert(t["hour"] == 10);
assert(t["minute"] == 20);
assert(t["second"] == 30);
assert(t["millisecond"] == 120);
