
//
println("Test List type");

//
var x = [1, 2, 3, 4];
assert(x.size() == 4);
assert(x[0] == 1);
assert(x[1] == 2);
assert(x[2] == 3);
assert(x[3] == 4);

//
x = [1, 3.14, "abcd", Date(2001, 12, 31)];
assert(x.size() == 4);
assert(x[0] == 1);
assert(x[1] == 3.14);
assert(x[2] == "abcd");
assert(x[3] == Date(2001, 12, 31));

// auto increase List (one element)
x[4] = 123.456;
assert(x[4] == 123.456);
assert(x.size() == 5);

// auto increase List (3 elements)
x[7] = 1200;
assert(x[5] == null);
assert(x[6] == null);
assert(x[7] == 1200);
assert(x.size() == 8);

// auto increase List (3 elements)
x[5] = 1024;
assert(x[5] == 1024);
assert(x.size() == 8);

x[100] = 1;

//
assert(x.indexOf(1) == 0);
assert(x.indexOf(3.14) == 1);
assert(x.indexOf("abcd") == 2);
assert(x.indexOf(Date(2001, 12, 31)) == 3);
assert(x.indexOf(123.456) == 4);
assert(x.indexOf(1024) == 5);
assert(x.indexOf(null) == 6);
assert(x.indexOf(1200) == 7);
